version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: apiary
      POSTGRES_PASSWORD: apiary123
      POSTGRES_DB: apiary_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth_service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://apiary:apiary123@postgres:5432/apiary_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  hive_service:
    build:
      context: .
      dockerfile: services/hive/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://apiary:apiary123@postgres:5432/apiary_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - auth_service

  monitoring_service:
    build:
      context: .
      dockerfile: services/monitoring/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://apiary:apiary123@postgres:5432/apiary_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - auth_service

  notification_service:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - auth_service

volumes:
  postgres_data: 